// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface CheckoutSession {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  checkout_ref?: unknown;
  fixture_status?: string;
  provider_status?: string;
  redirect_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Customer {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  customer_ref?: unknown;
  entitlement_grant?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Download {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  download_ref?: unknown;
  fixture_status?: string;
  download_issue?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Email {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  email_ref?: unknown;
  fixture_status?: string;
  email_resend?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Entitlement {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  entitlement_ref?: unknown;
  fixture_status?: string;
  entitlement_revoke?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface License {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  license_ref?: unknown;
  fixture_status?: string;
  license_revoke?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Order {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  order_ref?: unknown;
  fixture_status?: string;
  payment_status?: string;
  total_amount?: number;
  lines?: unknown;
  order_refund?: unknown;
  order_cancel?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Product {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  commerce_ref?: unknown;
  variants?: unknown;
  mika_catalog_sync?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface StockItem {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  stock_ref?: unknown;
  quantities?: unknown;
  stock_adjust?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface WebhookEvent {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  webhook_ref?: unknown;
  fixture_status?: string;
  webhook_replay?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    checkout_sessions: CheckoutSession;
    customers: Customer;
    downloads: Download;
    emails: Email;
    entitlements: Entitlement;
    licenses: License;
    orders: Order;
    products: Product;
    stock_items: StockItem;
    webhooks: WebhookEvent;
  }
}